
server:
  port: 8080  #tomcat端口

spring: #springboot的配置
  datasource: #定义数据源
    name: test
    #127.0.0.1为本机测试的ip，3306是mysql的端口号。serverTimezone是定义时区，照抄就好，mysql高版本需要定义这些东西
    #useSSL也是某些高版本mysql需要问有没有用SSL连接
    url: jdbc:mysql://localhost:3306/leanwork?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root  #数据库用户名，root为管理员
    password: root #该数据库用户的密码
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:  #mybatyis的配置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.com.mxxk.mapper

  #配置分页插件pagehelper
  pagehelper:
      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql
